package com.kchen52.yetanothertranslinkapp;

import android.os.Bundle;
import android.support.design.widget.FloatingActionButton;
import android.support.design.widget.Snackbar;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;
import android.view.View;
import android.widget.ListView;

import java.util.ArrayList;

public class BusListActivity extends AppCompatActivity {

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_bus_list);
		Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
		setSupportActionBar(toolbar);

		ListView listView = (ListView)findViewById(R.id.busListView);

		CustomAdapter adapter = new CustomAdapter(this, getBusListArray());
		listView.setAdapter(adapter);
	}

	private Model[] getBusListArray() {
		Model[] busList = new Model[230];
		busList[0] = new Model("002 - MACDONALD/DOWNTOWN", 0);
		busList[1] = new Model("003 - MAIN/DOWNTOWN", 0);
		busList[2] = new Model("004 - POWELL/DOWNTOWN/UBC", 0);
		busList[3] = new Model("005 - ROBSON/DOWNTOWN", 0);
		busList[4] = new Model("006 - DAVIE/DOWNTOWN", 0);
		busList[5] = new Model("007 - NANAIMO STN/DUNBAR", 0);
		busList[6] = new Model("008 - FRASER/DOWNTOWN", 0);
		busList[7] = new Model("009 - BDRY/COMM-BWY/GRAN/ALMA/UBC", 0);
		busList[8] = new Model("010 - GRANVILLE/DOWNTOWN", 0);
		busList[9] = new Model("014 - HASTINGS/UBC", 0);
		busList[10] = new Model("015 - CAMBIE/OLYMPIC VILLAGE STN", 0);
		busList[11] = new Model("016 - 29TH AVENUE STN/ARBUTUS", 0);
		busList[12] = new Model("017 - OAK/DOWNTOWN", 0);
		busList[13] = new Model("019 - METROTOWN STN/STANLEY PARK", 0);
		busList[14] = new Model("020 - VICTORIA/DOWNTOWN", 0);
		busList[15] = new Model("022 - KNIGHT/DOWNTOWN", 0);
		busList[16] = new Model("025 - BRENTWOOD STN/UBC", 0);
		busList[17] = new Model("026 - JOYCE STN/29TH AVENUE STN", 0);
		busList[18] = new Model("027 - KOOTENAY LOOP/JOYCE STN", 0);
		busList[19] = new Model("028 - CAP UNIVERSIT/PHIBBS EXCH/JOYCE STN", 0);
		busList[20] = new Model("029 - ELLIOTT/29TH AVENUE STN", 0);
		busList[21] = new Model("032 - DUNBAR/DOWNTOWN", 0);
		busList[22] = new Model("033 - 29 AVE STN/ UBC", 0);
		busList[23] = new Model("041 - JOYCE STN/CROWN/UBC", 0);
		busList[24] = new Model("043 - JOYCE STN/UBC", 0);
		busList[25] = new Model("044 - UBC/DOWNTOWN", 0);
		busList[26] = new Model("049 - METROTOWN STN/DUNBAR LOOP/UBC", 0);
		busList[27] = new Model("050 - WATERFRONT STN/FALSE CREEK SOUTH", 0);
		busList[28] = new Model("084 - UBC/VCC STATION", 0);
		busList[29] = new Model("096 - GUILDFORD EX/ NEWTON EX (B-LINE)", 0);
		busList[30] = new Model("097 - COQUITLAM STN/LOUGHEED STN (B-LINE)", 0);
		busList[31] = new Model("099 - COMMERCIAL-BROADWAY/UBC (B-LINE)", 0);
		busList[32] = new Model("100 - 22ND ST STN/MARPOLE LOOP", 0);
		busList[33] = new Model("101 - LOUGHEED STN/22ND ST STN", 0);
		busList[34] = new Model("104 - 22ND ST STN/ANNACIS ISLAND", 0);
		busList[35] = new Model("106 - NEW WESTMINSTER STN/METROTOWN STN", 0);
		busList[36] = new Model("110 - LOUGHEED STN/METROTOWN STN", 0);
		busList[37] = new Model("112 - EDMONDS STN/NEW WEST STN", 0);
		busList[38] = new Model("116 - EDMONDS STN/METROTOWN STN", 0);
		busList[39] = new Model("123 - NEW WEST STN/BRENTWOOD STN", 0);
		busList[40] = new Model("125 - PATTERSON STN/BCIT", 0);
		busList[41] = new Model("128 - BRAID STN/22ND STREET STN", 0);
		busList[42] = new Model("129 - PATTERSON STN/EDMONDS STN", 0);
		busList[43] = new Model("130 - METROTOWN/HASTINGS/KOOTENAY/CAP U", 0);
		busList[44] = new Model("134 - LAKE CITY STN/BRENTWOOD STN", 0);
		busList[45] = new Model("135 - SFU/BURRARD STN", 0);
		busList[46] = new Model("136 - LOUGHEED STN/BRENTWOOD STN", 0);
		busList[47] = new Model("143 - COQUITLAM STN/SFU", 0);
		busList[48] = new Model("144 - SFU/METROTOWN STN", 0);
		busList[49] = new Model("145 - SFU/PRODUCTION STN", 0);
		busList[50] = new Model("151 - COQUITLAM STN/LOUGHEED STN", 0);
		busList[51] = new Model("152 - COQUITLAM STN/LOUGHEED STN", 0);
		busList[52] = new Model("153 - COQUITLAM REC CTR/BRAID STN", 0);
		busList[53] = new Model("155 - BRAID STN/22ND STREET STN", 0);
		busList[54] = new Model("156 - BRAID STN/LOUGHEED STN", 0);
		busList[55] = new Model("157 - COQUITLAM REC CENTRE/LOUGHEED STN", 0);
		busList[56] = new Model("159 - PORT COQUITLAM STN/BRAID STN", 0);
		busList[57] = new Model("160 - PORT COQUITLAM STN/VANCOUVER", 0);
		busList[58] = new Model("169 - COQUITLAM STN/BRAID STN", 0);
		busList[59] = new Model("178 - COQUITLAM STN/PORT MOODY STN", 0);
		busList[60] = new Model("188 - COQUITLAM STN/PORT COQUITLAM STN", 0);
		busList[61] = new Model("190 - COQUITLAM STN/VANCOUVER", 0);
		busList[62] = new Model("209 - UPPER LYNN VALLEY/VANCOUVER", 0);
		busList[63] = new Model("210 - UPPER LYNN VALLEY/VANCOUVER", 0);
		busList[64] = new Model("211 - SEYMOUR/PHIBBS EXCH/VANCOUVER", 0);
		busList[65] = new Model("212 - DEEP COVE/PHIBBS EXCH", 0);
		busList[66] = new Model("214 - BLUERIDGE/PHIBBS EXCH/VANCOUVER", 0);
		busList[67] = new Model("227 - LYNN VALLEY CENTRE/PHIBBS EXCHANGE", 0);
		busList[68] = new Model("228 - LYNN VALLEY/LONSDALE QUAY", 0);
		busList[69] = new Model("229 - LYNN VALLEY/LONSDALE QUAY", 0);
		busList[70] = new Model("230 - UPPER LONSDALE/LONSDALE QUAY", 0);
		busList[71] = new Model("231 - HARBOURSIDE/LONSDALE QUAY", 0);
		busList[72] = new Model("232 - GROUSE MOUNTAIN/PHIBBS EXCH", 0);
		busList[73] = new Model("236 - GROUSE MOUNTAIN/LONSDALE QUAY", 0);
		busList[74] = new Model("239 - CAPILANO UNIVERSITY/PARK ROYAL", 0);
		busList[75] = new Model("240 - 15TH STREET/VANCOUVER", 0);
		busList[76] = new Model("241 - UPPER LONSDALE/VANCOUVER", 0);
		busList[77] = new Model("242 - LYNN VALLEY/VANCOUVER", 0);
		busList[78] = new Model("246 - LONSDALE QUAY/HIGHLAND/VANCOUVER", 0);
		busList[79] = new Model("247 - UPPER CAPILANO/GROUSE/VANCOUVER", 0);
		busList[80] = new Model("250 - HORSESHOE BAY/DUNDARAVE/VANCOUVER", 0);
		busList[81] = new Model("251 - QUEENS/PARK ROYAL", 0);
		busList[82] = new Model("252 - INGLEWOOD/PARK ROYAL", 0);
		busList[83] = new Model("253 - CAULFEILD/VANCOUVER/PARK ROYAL", 0);
		busList[84] = new Model("254 - BRITISH PROPERTIES/PARK ROYAL/VAN", 0);
		busList[85] = new Model("255 - DUNDARAVE/CAPILANO UNIVERSITY", 0);
		busList[86] = new Model("256 - FOLKSTONE WY/WHITBY ESTATE/SPURAWAY", 0);
		busList[87] = new Model("257 - HORSESHOE BAY/VANCOUVER EXPRESS", 0);
		busList[88] = new Model("258 - UBC/WEST VANCOUVER", 0);
		busList[89] = new Model("259 - LIONS BAY/HORSESHOE BAY", 0);
		busList[90] = new Model("301 - NEWTON EXCHANGE/BRIGHOUSE STATION", 0);
		busList[91] = new Model("311 - SCOTTSDALE/BRIDGEPORT STN", 0);
		busList[92] = new Model("312 - SCOTTSDALE/SCOTT ROAD STN", 0);
		busList[93] = new Model("314 - SURREY CENTRAL/SUNBURY", 0);
		busList[94] = new Model("316 - SURREY CENTRAL STN/SCOTTSDALE", 0);
		busList[95] = new Model("319 - SCOTT ROAD STN/NEWTON EXCHA", 0);
		busList[96] = new Model("320 - LANGLEY/FLEETWOOD/SURREY CTRL STN", 0);
		busList[97] = new Model("321 - WHITE ROCK/NEWTON/SURREY CTRL STN", 0);
		busList[98] = new Model("323 - NEWTON EXCH/SURREY CENTRAL STN", 0);
		busList[99] = new Model("324 - NEWTON EXCH/SURREY CENTRAL STN", 0);
		busList[100] = new Model("325 - NEWTON EXCH/SURREY CENTRAL STN", 0);
		busList[101] = new Model("326 - GUILDFORD/SURREY CENTRAL STN", 0);
		busList[102] = new Model("329 - SURREY CENTRAL STN/SCOTTSDALE", 0);
		busList[103] = new Model("335 - NEWTON/SURREY CENTRAL STN", 0);
		busList[104] = new Model("337 - FRASER HEIGHTS/GUILDFORD/SURREY CTR", 0);
		busList[105] = new Model("340 - SCOTTSDALE/22ND ST STN", 0);
		busList[106] = new Model("341 - GUILDFORD/NEWTON EXCH", 0);
		busList[107] = new Model("342 - LANGLEY CENTRE/NEWTON EXCHANGE", 0);
		busList[108] = new Model("345 - KING GEORGE STN/WHITE ROCK CENTRE", 0);
		busList[109] = new Model("351 - CRESCENT BEACH/BRIDGEPORT STN", 0);
		busList[110] = new Model("352 - OCEAN PARK /BRIDGEPORT STN", 0);
		busList[111] = new Model("354 - WHITE ROCK SOUTH/BRIDGEPORT STATION", 0);
		busList[112] = new Model("364 - LANGLEY CTR/ SCOTTSDALE EX", 0);
		busList[113] = new Model("375 - WHITE ROCK/WHITE ROCK STH/GUILDFORD", 0);
		busList[114] = new Model("388 - 22ST STN/CARVOLTH EXCH", 0);
		busList[115] = new Model("391 - SCOTTSDALE/SCOTT ROAD STN", 0);
		busList[116] = new Model("393 - NEWTON EXCH/SURREY CENTRAL STN", 0);
		busList[117] = new Model("394 - WHITE ROCK/KING GEORGE STN EXPRESS", 0);
		busList[118] = new Model("395 - LANGLEY CENTRE/KING GEORGE STN", 0);
		busList[119] = new Model("401 - ONE ROAD/GARDEN CITY", 0);
		busList[120] = new Model("402 - TWO ROAD/BRIGHOUSE STATION", 0);
		busList[121] = new Model("403 - BRIDGEPORT STN/THREE ROAD", 0);
		busList[122] = new Model("404 - FOUR ROAD/BRIGHOUSE STATION", 0);
		busList[123] = new Model("405 - FIVE ROAD/CAMBIE", 0);
		busList[124] = new Model("407 - GILBERT/BRIDGEPORT", 0);
		busList[125] = new Model("410 - 22ND ST STN/QUEENSBOROUGH/RAILWAY", 0);
		busList[126] = new Model("430 - METROTOWN/BRIGHOUSE STATION", 0);
		busList[127] = new Model("480 - UBC/BRIDGEPORT STN", 0);
		busList[128] = new Model("501 - LANGLEY CENTRE/SURREY CENTRAL STN", 0);
		busList[129] = new Model("502 - LANGLEY CENTRE/SURREY CENTRAL STN", 0);
		busList[130] = new Model("503 - ALDERGROVE/SURREY CENTRAL STN", 0);
		busList[131] = new Model("509 - WALNUT GROVE/SURREY CENTRAL STN", 0);
		busList[132] = new Model("531 - WHITE ROCK CENTRE/WILLOWBROOK", 0);
		busList[133] = new Model("555 - CARVOLTH EXCH / LOUGHEED STN", 0);
		busList[134] = new Model("590 - LANGLEY SOUTH/LANGLEY CENTRE", 0);
		busList[135] = new Model("595 - MAPLE MEADOWS STN/LANGLEY CENTRE", 0);
		busList[136] = new Model("601 - SOUTH DELTA/BOUNDARY BAY/BRIDGEPORT", 0);
		busList[137] = new Model("602 - TSAWWASSEN HEIGHTS/BRIDGEPORT", 0);
		busList[138] = new Model("603 - BEACH GROVE/BRIDGEPORT", 0);
		busList[139] = new Model("604 - ENGLISH BLUFF/BRIDGEPORT", 0);
		busList[140] = new Model("606 - LADNER RING", 0);
		busList[141] = new Model("608 - LADNER RING", 0);
		busList[142] = new Model("609 - TSAWWASSEN FIRST NATION/SOUTH DELTA", 0);
		busList[143] = new Model("620 - TSAWWASSEN FERRY/BRIDGEPORT STATION", 0);
		busList[144] = new Model("640 - LADNER EXCH/SCOTT ROAD STN", 0);
		busList[145] = new Model("701 - HANEY/MAPLE RIDGE EAST/COQ STN", 0);
		busList[146] = new Model("791 - HANEY PLACE/BRAID STN", 0);
		busList[147] = new Model("804 - HOLY CROSS SCHOOL", 0);
		busList[148] = new Model("807 - SCHOOL SPECIAL", 0);
		busList[149] = new Model("828 - KWANTLEN PARK SCHOOL", 0);
		busList[150] = new Model("840 - BROOKSWOOD SCHOOL", 0);
		busList[151] = new Model("848 - PORT MOODY SS", 0);
		busList[152] = new Model("855 - ELGIN PARK SCHOOL SPECIAL", 0);
		busList[153] = new Model("861 - RIVERSIDE SCHOOL", 0);
		busList[154] = new Model("863 - TERRY FOX/ARCH CARNEY", 0);
		busList[155] = new Model("864 - LORD TWEEDSMUIR SCHOOL", 0);
		busList[156] = new Model("865 - ROBERTSON", 0);
		busList[157] = new Model("867 - HERITAGE WOODS SCHOOL", 0);
		busList[158] = new Model("880 - WINDSOR SCHOOL SPECIALS", 0);
		busList[159] = new Model("881 - CARSON GRAHAM SCHOOL SPECIALS", 0);
		busList[160] = new Model("C1 - HASTINGS & GILMORE/KOOTENAY LOOP", 0);
		busList[161] = new Model("C2 - CAPITOL HILL/HASTINGS AT GILMORE", 0);
		busList[162] = new Model("C3 - QUAYSIDE/VICTORIA HILL", 0);
		busList[163] = new Model("C4 - UPTOWN/NEW WESTMINSTER STATION", 0);
		busList[164] = new Model("C5 - ROYAL OAK STN/EDMONDS STN", 0);
		busList[165] = new Model("C6 - METROTOWN STN/SUNCREST", 0);
		busList[166] = new Model("C7 - METROTOWN STN/EDMONDS STN", 0);
		busList[167] = new Model("C9 - NEW WESTMINSTER STN/LOUGHEED STN", 0);
		busList[168] = new Model("C10 - BLUEWATER/SNUG COVE", 0);
		busList[169] = new Model("C11 - EAGLE CLIFF/SNUG COVE", 0);
		busList[170] = new Model("C12 - LIONS BAY/CAULFEILD", 0);
		busList[171] = new Model("C15 - INDIAN RIVER/PHIBBS EXCH", 0);
		busList[172] = new Model("C18 - WEST MALL/UBC LOOP", 0);
		busList[173] = new Model("C19 - ALMA/SPANISH BANKS", 0);
		busList[174] = new Model("C20 - TOTEM PARK/UBC LOOP", 0);
		busList[175] = new Model("C21 - YALETOWN/BEACH", 0);
		busList[176] = new Model("C23 - YALETOWN/DAVIE/MAIN ST STN", 0);
		busList[177] = new Model("C24 - PORT MOODY STN/LOUGHEED STN", 0);
		busList[178] = new Model("C25 - IOCO/PORT MOODY STN", 0);
		busList[179] = new Model("C26 - BELCARRA/PORT MOODY STN", 0);
		busList[180] = new Model("C27 - COQUITLAM STN/PORT MOODY STN", 0);
		busList[181] = new Model("C28 - COQUITLAM STN/PORT MOODY STN", 0);
		busList[182] = new Model("C29 - COQUITLAM STN/PARKWAY BOULEVARD", 0);
		busList[183] = new Model("C30 - LAFARGE PARK/COQUITLAM STN", 0);
		busList[184] = new Model("C36 - PORT COQ STN/PORT COQ SOUTH", 0);
		busList[185] = new Model("C37 - PORT COQ STN/PRAIRIE/RIVERSIDE", 0);
		busList[186] = new Model("C38 - COQ STN/RIVER SPR/PRAIRIE/POCO", 0);
		busList[187] = new Model("C40 - MERIDIAN/PORT COQUITLAM STN", 0);
		busList[188] = new Model("C41 - MEADOWTOWN/MAPLE MDWS STN/P MDW CTR", 0);
		busList[189] = new Model("C43 - HANEY PL/MAPLE MDWS STN/MEADOWTOWN", 0);
		busList[190] = new Model("C44 - HANEY PL/MAPLE MDWS STN/MEADOWTOWN", 0);
		busList[191] = new Model("C45 - COTTONWOOD/HANEY PLACE", 0);
		busList[192] = new Model("C46 - ALBION/HANEY PLACE", 0);
		busList[193] = new Model("C47 - ALOUETTE/HANEY PLACE", 0);
		busList[194] = new Model("C48 - THORNHILL/HANEY PLACE", 0);
		busList[195] = new Model("C49 - RUSKIN/HANEY PLACE", 0);
		busList[196] = new Model("C50 - OCEAN PARK/PEACE ARCH HOSPITAL", 0);
		busList[197] = new Model("C51 - OCEAN PARK/WHITE ROCK CENTRE", 0);
		busList[198] = new Model("C52 - SEASIDE/WHITE ROCK CENTRE", 0);
		busList[199] = new Model("C53 - CRANLEY DRIVE/WHITE ROCK CENTRE", 0);
		busList[200] = new Model("C60 - LANGLEY CENTRE/LANGLEY HOSPITAL", 0);
		busList[201] = new Model("C61 - LANGLEY CENTRE/BROOKSWOOD", 0);
		busList[202] = new Model("C62 - LANGLEY CENTRE/WALNUT GROVE", 0);
		busList[203] = new Model("C63 - LANGLEY CENTRE/FERNRIDGE", 0);
		busList[204] = new Model("C64 - LANGLEY CTR/WILLOWBROOK", 0);
		busList[205] = new Model("C70 - CLOVERDALE/WILLOWBROOK", 0);
		busList[206] = new Model("C71 - SURREY CNTRL/SCOTT RD STN", 0);
		busList[207] = new Model("C73 - GUILDFORD/ SURREY CNTRL STN", 0);
		busList[208] = new Model("C75 - NEWTON EX/SCOTTSDALE", 0);
		busList[209] = new Model("C76 - SCOTTSDALE/LADNER EX", 0);
		busList[210] = new Model("C84 - ENGLISH BLUFF/SOUTH DELTA REC CENTR", 0);
		busList[211] = new Model("C86 - LADNER SOUTH/LADNER EXCH", 0);
		busList[212] = new Model("C87 - EAST LADNER/LADNER EXCH", 0);
		busList[213] = new Model("C88 - LADNER NORTH/LADNER EXCH", 0);
		busList[214] = new Model("C89 - BOUNDARY BAY/SOUTH DELTA REC CENTRE", 0);
		busList[215] = new Model("C92 - BRIDGEPORT STATION/SEA ISLAND SOUTH", 0);
		busList[216] = new Model("C93 - RIVERPORT/STEVESTON", 0);
		busList[217] = new Model("C94 - RICHMOND OVAL/BRIGHOUSE STN", 0);
		busList[218] = new Model("C96 - EAST CAMBIE/BRIGHOUSE STATION", 0);
		busList[219] = new Model("C98 - KINGSWOOD/22ND ST STN", 0);
		busList[220] = new Model("N8 - DOWNTOWN/FRASER NIGHTBUS", 0);
		busList[221] = new Model("N9 - DOWNTOWN/COQUITLAM STN NIGHTBUS", 0);
		busList[222] = new Model("N10 - DOWNTOWN/RICHMOND NIGHTBUS", 0);
		busList[223] = new Model("N15 - DOWNTOWN/CAMBIE NIGHTBUS", 0);
		busList[224] = new Model("N17 - DOWNTOWN/UBC NIGHTBUS", 0);
		busList[225] = new Model("N19 - DOWNTOWN/SURREY CNTRL STN NIGHTBUS", 0);
		busList[226] = new Model("N20 - DOWNTOWN/VICTORIA NIGHTBUS", 0);
		busList[227] = new Model("N22 - DOWNTOWN/MACDONALD NIGHTBUS", 0);
		busList[228] = new Model("N24 - DOWNTOWN/ LYNN VALLEY NIGHTBUS", 0);
		busList[229] = new Model("N35 - DOWNTOWN/SFU NIGHTBUS", 0);
		return busList;
	}
}
